jQuery(document).ready(function(){
$("#listjavascript").click(function()
{
  $(".javascript").removeClass();
 $(".javascript").show();
});
$("#listoperators").click(function(){
  $(".operators").removeClass();
  $(".operators").show();
  $(".operators").hide();
});
$("#listcomment").click(function(){
  $(".comments").removeClass();
  $(".comments").show();
  $(".comments").hide();
});
});
