jQuery(document).ready(function(){
$("#listjavascript").click(function()
{
  $(".javascript").removeClass();
 $(".javascript").slideUp("slow");
});
$("#listoperators").click(function(){
  $(".operators").slideUp("slow");
});
$("#listcomment").click(function(){
  $(".comments").slideUp("slow");
});
$("#listvariables").click(function(){
  $(".variables").slideUp("slow");
});
});
